/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class magic_guard_CodeGuardMoJo */

#ifndef _Included_magic_guard_CodeGuardMoJo
#define _Included_magic_guard_CodeGuardMoJo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magic_guard_CodeGuardMoJo
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_magic_guard_CodeGuardMoJo_encrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
